In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [35]:
sent=['the cat sat on the mat',
      'the dog sat on the log',
      'the glass is on the table',
      'these are the three sentences']

In [36]:
#Define the vocabulary size
voc_size=1000

In [37]:
#one hot representation
onehot_repr=[one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[271, 266, 49, 707, 271, 946], [271, 219, 49, 707, 271, 775], [271, 98, 980, 707, 271, 86], [316, 803, 271, 277, 476]]


In [38]:
#word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [39]:
import numpy as np

In [44]:
sent_length=6
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[271 266  49 707 271 946]
 [271 219  49 707 271 775]
 [271  98 980 707 271  86]
 [  0 316 803 271 277 476]]


In [45]:
#feature representation using embedding
dim=10

In [46]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [48]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [49]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step


array([[[-0.04247639,  0.00342288, -0.03170754,  0.010906  ,
          0.0028713 ,  0.01154473,  0.04443317, -0.00832504,
          0.01247207,  0.00485741],
        [-0.02468042,  0.02433089, -0.00729307, -0.01095178,
         -0.02122358, -0.00474353, -0.03443457,  0.00765202,
          0.00641458,  0.01702381],
        [-0.04767749, -0.02910818, -0.03688664, -0.04051676,
          0.0475605 , -0.00039821, -0.04819259, -0.04246793,
         -0.01267665,  0.02514908],
        [-0.02704698,  0.00856958,  0.00308015, -0.03981719,
          0.04569629,  0.0036839 , -0.00139326,  0.02646091,
         -0.03605112, -0.00052435],
        [-0.04247639,  0.00342288, -0.03170754,  0.010906  ,
          0.0028713 ,  0.01154473,  0.04443317, -0.00832504,
          0.01247207,  0.00485741],
        [ 0.00399976,  0.03696051, -0.012662  ,  0.01925495,
         -0.04163538, -0.00787906,  0.04127394,  0.01275892,
         -0.01279502,  0.03318617]],

       [[-0.04247639,  0.00342288, -0.03170754,  0

In [50]:
model.predict(embedded_docs[0].reshape(1,6))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([[[-0.04247639,  0.00342288, -0.03170754,  0.010906  ,
          0.0028713 ,  0.01154473,  0.04443317, -0.00832504,
          0.01247207,  0.00485741],
        [-0.02468042,  0.02433089, -0.00729307, -0.01095178,
         -0.02122358, -0.00474353, -0.03443457,  0.00765202,
          0.00641458,  0.01702381],
        [-0.04767749, -0.02910818, -0.03688664, -0.04051676,
          0.0475605 , -0.00039821, -0.04819259, -0.04246793,
         -0.01267665,  0.02514908],
        [-0.02704698,  0.00856958,  0.00308015, -0.03981719,
          0.04569629,  0.0036839 , -0.00139326,  0.02646091,
         -0.03605112, -0.00052435],
        [-0.04247639,  0.00342288, -0.03170754,  0.010906  ,
          0.0028713 ,  0.01154473,  0.04443317, -0.00832504,
          0.01247207,  0.00485741],
        [ 0.00399976,  0.03696051, -0.012662  ,  0.01925495,
         -0.04163538, -0.00787906,  0.04127394,  0.01275892,
         -0.01279502,  0.03318617]]], dtype=float32)